### ISSUE TITLE
Allow the visitor to abort or cease recursion

### ISSUE THREAD

**Issue by connor4312** [microsoft/node-jsonc-parser#30]
I'm working on a code lens that should decorate npm scripts. For this, I'm parsing a JSON file, and only want the top level "scripts" key. I'm entirely uninterested in other properties, and once I have that I'm happy to abort parsing.

It'd be nice to be able to return a value from JSONVisitor methods which could indicate that we want to cease recursion on the current node, or abort parsing entirely.

**Comment by aeschli** [comment]
To abort, throw an exception and catch it in a try/catch around parse.

To cease recursion, we could add a return value on onObjectBegin and onArrayBegin. If you want to make a PR, I'm happy to take it.

**Comment by Vbbab** [comment]
Just wondering, how would this work? Would returning, say, `false`, from `onObjectBegin` prevent further parsing of the current object? In that case, would [`parseObject()`](https://github.com/microsoft/node-jsonc-parser/blob/e82ebd90d91f026521d88d11c9749e2f02b9a79f/src/impl/parser.ts#L542) in `visit()` simply return `false`?

**Comment by aeschli** [comment]
The object will be parsed, just the visitor won't get any callbacks for any of the properties of the object
Internally, parseObject still return true or false, based on the validity of the input.

**Comment by Vbbab** [comment]
Alright, so as per my understanding, if at the start of an object I return `false` (meaning don't give callbacks) for onObjectBegin, the ONLY other call I will get for that object is onObjectEnd, and nothing for the inside (not even onSeparator, onLiteralValue, etc.)?

Asking this as I'm actually currently trying to work on a PR to add this, and just want to make sure I understand things correctly.

Thanks!

**Comment by aeschli** [comment]
Yes, correct.

**Comment by Vbbab** [comment]
Alright, sorry that it's been quite a while - I've had to put this issue on the back burner for a bit due to a lack of time.

However, here is a quick update -- I'm currently working on testing an implementation for this feature I've got, but it seems like my IDE is throwing out a strange error under `src/test/json.test.ts`:

Specifically, on both L90 and L93:
https://github.com/microsoft/node-jsonc-parser/blob/b6b34ba39da3f5bee17d41004c03a86686dade4c/src/test/json.test.ts#L90-L93

Shouldn't `onObjectBegin` and `onArrayBegin` normally be functions returning `void`? Yet the `noArgHalderWithPath` function returns just a number?? I'm quite confused as to how the testing mechanism is supposed to work here...

In addition, in `src/impl/parser.ts`, there are also some of what appear to be callback adapters:
https://github.com/microsoft/node-jsonc-parser/blob/b6b34ba39da3f5bee17d41004c03a86686dade4c/src/impl/parser.ts#L393-L404

According to the function signature, these should return functions of type `() => void`, yet if `visitFunction` is `null` or otherwise falsy, they all seem to return `() => true`, violating the signature. Is the entire point to prevent `visitFunction` from being omitted? If so, why make it optional? (My IDE doesn't error here though, so perhaps it's just that I don't understand TypeScript enough😅)

Sorry if all of this is a lot... Thanks, though! 😄

**Comment by Vbbab** [comment]
Alright, I submitted a PR -- feel free to take a look!

**Comment by Vbbab** [comment]
Update -- since the above PR #88 has been merged and the feature implemented into the next version, I believe we should be able to close this issue?

**Comment by aeschli** [comment]
Yes, thanks!
