### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by justinmchase** [microsoft/node-jsonc-parser#74]
A simple example of using this library would go a long way.

It would be nice to see:

1. parse a string
2. modify a single field
3. stringify

**Comment by felixhaeberle** [comment]
@aeschli Thank you for providing such a great library, but I also struggle on using this piece of code:

I want to parse this code:

```json
{
  "recommendations": [
    // single comment
    "example.example-extension"
  ]
  /* second comment */
}
```

- modify the recommendation array, 
- and then write back to this file **while preserving the comments**.

How can this be achieved? I tried multiple ways with `parse`, `applyEdits`, `findNodeAtLocation` & more but had no success preserving the comments – that's funny because I use the library exactly for that reason and otherwise could choose any other of even native `JSON` functionality. 😅

The documentation truly lacks a comprehensive example of how to use this library.
Happy to contribute an example if you explain it to me here. Thanks 🙏

**Comment by kvnloughead** [comment]
I would also love some examples. I've managed to use it like this (in a Deno app).

```
const text = await readFile(file);
const edits = modify(text, ["foo", "bar"], "baz", {});
await Deno.writeTextFile(file, applyEdits(text, edits));
```

It successfully updates the jsonc, but without any formatting. Also, line comments tend to wind up on the wrong line. It's not clear (to me) from the docs how to piece this together.

**Comment by kvnloughead** [comment]
Well, I think I figured out a way to do it, seems to work pretty well. I'm sure it's less than optimal. 

```js
// read jsonc file
const text = await readFile(file);

// make edits and apply them
const edits = modify(text, [...keys], value, {});
const updated = applyEdits(text, edits);

// format the updated text
const formatted = format(updated, undefined, {});
const res = applyEdits(updated, formatted)

// write changes to file
await Deno.writeTextFile(file, res);
```
